### ISSUE TITLE
Unprefixed ids

### ISSUE THREAD

**Issue by appleton** [nolanlawson/relational-pouch#26]
This question is related to [this](https://github.com/nolanlawson/ember-pouch/issues/53).

I'm converting data between a pre-existing flat format and the nested `data` key which is used by relational pouch using [transform-pouch](https://github.com/nolanlawson/transform-pouch) which works great, but the issue I'm seeing is that relational-pouch expects all `_id`s to be prefixed with (in my case) `note_2_`.

None of the existing data follows this convention, they all just use standard uuids. Converting the id's with transform-pouch does not help here, presumably because relational-pouch relies on the prefix to lookup data. Is there any way around this which does not involve migrating the ids of all my existing data?

Perhaps I should be writing a PR to transform-pouch to add handlers which only apply to replication?

**Comment by nolanlawson** [comment]
You can use the [`parseDocID()`](https://github.com/nolanlawson/relational-pouch#dbrelparsedociddocid) and [`makeDocID()`](https://github.com/nolanlawson/relational-pouch#dbrelmakedocidparsedid) functions to translate between relational-pouch's ID format and the underlying ID format.

That being said, `transform-pouch` doesn't change the ID of your documents, only the content, so I'm not sure where your problem is coming from.

> None of the existing data follows this convention, they all just use standard uuids.

Maybe your issue is that you are trying to use relational-pouch with a pre-existing non-relational-pouch database? It definitely doesn't work in that case; it assumes every operation you've done on the database has been through its `rel` API.

**Comment by appleton** [comment]
You know, I think you'e right. I've removed ember-pouch and written my own adapter which works just fine given the very simple data I'm dealing with.
