### ISSUE TITLE
Performance of loading a lot of results

### ISSUE THREAD

**Issue by marekkalnik** [nolanlawson/relational-pouch#32]
First of all - thanks for this plugin. It may be really useful, especially for local DBs on mobile devices, where it allows to limit the stored data, compared to "one big object" approach.

I have a use case that requires some more logic - we retrieve all objects, to run a filter function on them and use only a subset. RelationalPouch queries all objects with all their relations and so on, so the resulting memory usage and execution time become too significant.

I have made a fork that tries to solve this issue, by allowing an array of constraints: https://github.com/bamlab/relational-pouch/tree/feature/where-and-join
The solution can be extended/improved but this is the first idea. It could be further extended to only retrieve selected relations, hence the branch name.

Could you give me some feedback? What do you think of the problem itself and my proposed solution?

**Comment by rsutphin** [comment]
Have you tried using async relationships to limit the amount of data you load initially?

**Comment by nolanlawson** [comment]
Hm, maybe this could be solved by implementing `query` (https://github.com/nolanlawson/relational-pouch/issues/3)? Or do you really need to filter on relations rather than the docs themselves? I'm hesitant to add yet another option, especially one that's not directly applicable to `ember-pouch`. (Yes, ostensibly this plugin is unrelated to `ember-pouch`, but in practice my goal is to have them pretty deeply tied to one another, if possible.)

**Comment by nolanlawson** [comment]
Closing since this is more a question than an issue
