### ISSUE TITLE
Handle relations when deleting/updating an object.

### ISSUE THREAD

**Issue by akofman** [nolanlawson/relational-pouch#52]
I didn't inspect the code to know whether it is possible but would that make any sense to handle relations when deleting or updating an object ?

For instance, if we have a one-to-many relation between books and an author, If we delete one of these books, we should also remove its reference from the books array in the artist object.

Thoughts ?

**Comment by nolanlawson** [comment]
I think I explicitly designed this library not to handle that, because I consider it a concern of application code. Also this is kinda how ember-data is designed, hence why I did this.

It's also worth pointing out that app code will still have to deal with these kinds of scenarios, e.g. in the case where a child document becomes out of sync with a parent document (either because replication only partially succeeded due to a flaky network, or there were conflicts, etc.).

Closing since I think this is out-of-scope for relational pouch, but thanks for opening the issue!
